### ISSUE TITLE
Wrong interpretation of Log Energy values

### ISSUE THREAD

**Issue by altelch** [joba-1/Joba_ESmart3#15]
Hi,

in the Read Log struct you defined the energy values as unit32_t but in the documentation it's a struct 
```
typedef struct
{
Uint16 wHi16;
Uint16 wLow16;
}Uint32s;
```
So the returned values are short-swapped what explains my 65536Wh increments ;-)

Greetings,
                    Heiko.

**Comment by joba-1** [comment]
Hm, interesting. Same here.
In my doc/ there is only "low words in front, high word after".
Do you have a link to your documentation? Maybe there is more interesting stuff I haven't seen yet :)

Anyways, this will change shortly.
I'd rather not change the API/structs and just switch the relevant words in the get/set functions. Hope it works out...

Thanks for the hint!

**Comment by joba-1** [comment]
Log.dwRunTime seems to never change and I never looked at EngSave.
Do you use them and see the same problem?

**Comment by joba-1** [comment]
Energy values should be fine now. Published new version 4.1 on PlatformIO

**Comment by altelch** [comment]
Hi,

this is what I have: https://www.photovoltaikforum.com/core/attachment/79081-esmart3-mppt-solar-controller-communication-protocol-v14-pdf/

RunTime never changes. Noticed that, too. EngSave isn't used by me. So didn't notice. The wrong Log-Values caused interesting solar energy harvest today ;-)

Greetings and Thank you,
   
            Heiko.

**Comment by altelch** [comment]
Can confirm, is fixed.

**Comment by joba-1** [comment]
ok its the same doc - I just forgot about the code snippets.
Thanks for confirming - closing now
